In [2]:
# 1: Given a 1D NumPy array arr_1d, extract and print the first element.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [ ]:
#2: Given a 1D NumPy array arr_1d, extract and print the last three elements.

arr = np.array([1, 2, 3, 4, 5])
print(arr[2:])

[3 4 5]


In [7]:
#3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.

arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr3[1,2])

6


In [8]:
#4: Given a 2D NumPy array arr_2d, extract and print the first row.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0])

[1 2 3]


In [10]:
#5: Given a 2D NumPy array arr_2d, extract and print the last column.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:,-1])

[3 6 9]


In [12]:
#6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and third column.

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr[1,2,2])

18


In [13]:
#7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr[-1])

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
#1: Given a 2D NumPy array arr_2d, transpose the array and print the result.
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1=np.transpose(arr)
print(arr1)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#2: Reshape Array
#Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.
arr_1 = np.array([1, 2, 3, 4, 5, 6])
arr=np.reshape(arr_1,(3,2))
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#3: Resize Array
#Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr=np.resize(arr_1d,(3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 1]]


In [ ]:
#4: Flatten Array
#Given a 2D NumPy array arr_2d, flatten it and print the result.
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr=arr_2d.flatten()
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
#5: Transpose Array
#Given a 3D NumPy array arr_3d, transpose the array and print the result.

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
arr1=np.transpose(arr)
print(arr1)



[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


In [4]:
#6: Reshape Array
#Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr=np.reshape(arr_1d,(4,3))
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#7: Resize Array
#Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.
arr_2d = np.array([[1, 2], [3, 4]])
arr=np.resize(arr_2d,(4,4))
print(arr)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [6]:
#8: Flatten Array
#Given a 3D NumPy array arr_3d, flatten it and print the result.

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr=arr_3d.flatten()
print(arr)

[1 2 3 4 5 6 7 8]
