In [ ]:
#1: Create a NumPy array with 5 elements initialized with zeros.
import numpy as np
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
#2: Create a NumPy array with 3 rows and 4 columns initialized with ones.
arr1=np.zeros([3,4])
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#3: Create a 1D NumPy array containing numbers from 1 to 10.
arr2=np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#4: Create a 2D NumPy array with dimensions 3x3 containing numbers from 1 to 9.
arr3=np.random.randint(1,10,size=(3,3))
arr3

array([[7, 5, 6],
       [9, 1, 4],
       [6, 2, 3]])

In [ ]:
#5: Create a 3D NumPy array with dimensions 2x3x4 containing random integers between 0 and 9.
arr4=np.random.randint(0,10,size=(2,3,4))
arr4

array([[[5, 0, 4, 5],
        [6, 8, 2, 8],
        [9, 8, 2, 5]],

       [[1, 5, 2, 3],
        [0, 3, 2, 6],
        [1, 7, 2, 0]]])

In [ ]:
#6: Create a NumPy array from a list containing elements [1, 2, 3, 4, 5].
arr5=np.arange(1,6)
arr5

array([1, 2, 3, 4, 5])

In [ ]:
#7: Convert a tuple (6, 7, 8, 9, 10) into a NumPy array.
a=(6,7,8,9,10)
b=np.array(a)
b

array([ 6,  7,  8,  9, 10])

In [ ]:
#8: Create a NumPy array with shape (4, 2) containing numbers from 0 to 7.
arr6=np.random.randint(0,7,size=(4,2))
print(arr6)
print(arr6.shape)

(4, 2)


In [ ]:
#9: Create a 3D NumPy array with shape (2, 3, 4) initialized with zeros.
arr7=np.zeros([2,3,4])
arr7

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#10: Create a 2D NumPy array with shape (3, 3) containing random floating-point numbers between 0 and 1.
arr8=np.random.random([3,3])
arr8

array([[0.29008793, 0.23710846, 0.28807558],
       [0.86609317, 0.06380158, 0.53309   ],
       [0.72251559, 0.5689852 , 0.271591  ]])

In [ ]:
#11: Create a NumPy array with shape (5,) containing numbers from 10 to 35, incrementing by 5.
arr9=np.arange(10,35,5)
arr9

array([10, 15, 20, 25, 30])

In [ ]:
#12: Create a NumPy array with shape (2, 5) containing numbers from -2 to 7
arr10=np.random.randint(-2,7,size=(2,5))
arr10

array([[ 2,  5,  2,  3, -2],
       [ 6, -1, -2, -2,  2]])

In [ ]:
#13: Create a 1D NumPy array with shape (10,) containing numbers from 100 to 109, and change its data type to float.
arr11=np.arange(100,110)
print(arr11)
new_arr=arr11.astype('float64')
print(new_arr)

[100 101 102 103 104 105 106 107 108 109]
[100. 101. 102. 103. 104. 105. 106. 107. 108. 109.]


In [ ]:
#14: Create a 2D NumPy array with shape (3, 4) initialized with ones, and then change its data type to int.
arr12=np.ones([3,4],dtype=int)
print(arr12)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
#15: Create a 3D NumPy array with shape (2, 2, 3) initialized with specified numbers [[1, 2, 3], [4, 5, 6]], and [[7, 8, 9], [10, 11, 12]].
arr13=np.array([[[1, 2, 3], [4, 5, 6]],
           [[7, 8, 9], [10, 11, 12]]])
arr13


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])